apiVersion: v1
kind: Service
metadata:
  name: travelmemoryfrontend
  namespace: frontend
spec:
  type: ClusterIP
  selector:
    app: TravelMemory-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000